-- V001: Presenter-owned baseline schema.
-- Business-key UNIQUE constraints are intentionally not part of the baseline; they are introduced through the later synchronized solution stages after the corresponding database behaviour is tested.

CREATE TABLE tbl_department (
    department_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_code VARCHAR(40) NOT NULL,
    department_name VARCHAR(150) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE tbl_member (
    member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_number VARCHAR(60) NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    email VARCHAR(150),
    fk_department BIGINT NOT NULL REFERENCES tbl_department(department_id),
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE tbl_author (
    author_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_code VARCHAR(40) NOT NULL,
    author_name VARCHAR(150) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE tbl_category (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_code VARCHAR(40) NOT NULL,
    category_name VARCHAR(120) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE tbl_publisher (
    publisher_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publisher_code VARCHAR(40) NOT NULL,
    publisher_name VARCHAR(150) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE tbl_book (
    book_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn VARCHAR(30) NOT NULL,
    title VARCHAR(200) NOT NULL,
    fk_author BIGINT NOT NULL REFERENCES tbl_author(author_id),
    fk_category BIGINT NOT NULL REFERENCES tbl_category(category_id),
    fk_publisher BIGINT NOT NULL REFERENCES tbl_publisher(publisher_id),
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE tbl_book_copy (
    book_copy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accession_number VARCHAR(60) NOT NULL,
    fk_book BIGINT NOT NULL REFERENCES tbl_book(book_id),
    status VARCHAR(30) NOT NULL DEFAULT 'AVAILABLE'
);

CREATE TABLE tbl_membership (
    membership_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    membership_number VARCHAR(60) NOT NULL,
    fk_member BIGINT NOT NULL REFERENCES tbl_member(member_id),
    membership_type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE tbl_reservation (
    reservation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_number VARCHAR(60) NOT NULL,
    fk_membership BIGINT NOT NULL REFERENCES tbl_membership(membership_id),
    fk_book BIGINT NOT NULL REFERENCES tbl_book(book_id),
    reserved_date DATE NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE tbl_book_issue (
    book_issue_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_number VARCHAR(60) NOT NULL,
    fk_membership BIGINT NOT NULL REFERENCES tbl_membership(membership_id),
    fk_book_copy BIGINT NOT NULL REFERENCES tbl_book_copy(book_copy_id),
    fk_reservation BIGINT REFERENCES tbl_reservation(reservation_id),
    issue_date DATE NOT NULL,
    due_date DATE NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE tbl_book_return (
    book_return_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_number VARCHAR(60) NOT NULL,
    fk_book_issue BIGINT NOT NULL REFERENCES tbl_book_issue(book_issue_id),
    return_date DATE NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'COMPLETED'
);

CREATE TABLE tbl_fine (
    fine_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fine_number VARCHAR(60) NOT NULL,
    fk_book_return BIGINT NOT NULL REFERENCES tbl_book_return(book_return_id),
    fk_membership BIGINT NOT NULL REFERENCES tbl_membership(membership_id),
    amount NUMERIC(12,2) NOT NULL,
    outstanding_amount NUMERIC(12,2) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'OUTSTANDING'
);

CREATE TABLE tbl_fine_payment (
    fine_payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_number VARCHAR(60) NOT NULL,
    fk_fine BIGINT NOT NULL REFERENCES tbl_fine(fine_id),
    amount NUMERIC(12,2) NOT NULL,
    paid_on DATE NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'POSTED'
);
